package axiom

// EndpointMap is one row of the Snowflake-middleware-endpoint → Axiom
// tables catalogue. Paths are the real 3-part Axiom prod identifiers
// (db.schema.table) so callers can jump straight to the right pool.
type EndpointMap struct {
	Method  string   `json:"method"`
	Path    string   `json:"path"`
	Summary string   `json:"summary"`
	Domain  string   `json:"domain"`
	Reads   []string `json:"reads,omitempty"`
	Writes  []string `json:"writes,omitempty"`
	Notes   string   `json:"notes,omitempty"`
}

// DefaultEndpointMap — validated against the LIVE Axiom prod cluster
// (axiom-prod-pg-cluster.rain.co.za:5433). All references are
// `db.schema.table`, discovered via docs/axiom/axiom-prod-catalogue.json
// (8,361 columns across 86 schemas). Tighten further as you trace the
// real middleware source.
//
// Keys that join across DBs (evidence from the catalogue):
//   - billing_account_id  — 72 tables across 10 DBs
//   - related_party_id    — 59 tables across 11 DBs
//   - financial_account_id — 60 tables across 6 DBs
//   - msisdn              — 52 tables across 8 DBs
//   - customer_id         — 40 tables across 5 DBs
var DefaultEndpointMap = []EndpointMap{
	// ── Topup / wallet adjustments ─────────────────────────────
	{Method: "POST", Path: "/topup/adjust-wallet", Summary: "Wallet Adjustment",
		Domain: "Billing",
		Reads:  []string{"account.account.billing_account", "account.account.account_balance"},
		Writes: []string{"account.account.account_balance_history", "payment.payment.payment"},
		Notes:  "Adjustment is written as a payment row + balance delta."},
	{Method: "POST", Path: "/service/wallet-adjustment/bucket-id/{bucketId}", Summary: "Wallet Adjustment (bucket)",
		Domain: "Billing",
		Reads:  []string{"account.account.billing_account"},
		Writes: []string{"account.account.account_balance", "account.account.account_balance_history"}},

	// ── SIM / device / port ────────────────────────────────────
	{Method: "POST", Path: "/service/{serviceId}/sim-swap/{userId}", Summary: "SIM Swap",
		Domain: "Service",
		Reads:  []string{"service.service.service_order", "service.service.resource_ref", "party.party.individual"},
		Writes: []string{"service.service.service_order", "service.service.service_order_item", "resource.ralf.request"}},
	{Method: "POST", Path: "/service/{productId}/device-swap", Summary: "Device Swap",
		Domain: "Service",
		Reads:  []string{"product.product.product", "service.service.resource_ref"},
		Writes: []string{"product.product.product_inventory_history", "service.service.service_order_item"}},
	{Method: "POST", Path: "/service/portin/{id}/reverse", Summary: "Port Reverse",
		Domain: "Service",
		Writes: []string{"porting.porting.port_request"},
		Notes:  "`porting` is a separate small DB — schema crawl pending."},
	{Method: "POST", Path: "/service/create-port-request", Summary: "Create Port Request",
		Domain: "Service",
		Writes: []string{"porting.porting.port_request"}},
	{Method: "POST", Path: "/service/cancel-port-request/{id}", Summary: "Cancel Port Request",
		Domain: "Service",
		Writes: []string{"porting.porting.port_request"}},

	// ── Top-ups ────────────────────────────────────────────────
	{Method: "POST", Path: "/service/top-up", Summary: "Top-up",
		Domain: "Billing",
		Writes: []string{"payment.payment.payment", "prepay.prepay.topup"}},
	{Method: "POST", Path: "/service/top-up-msisdn", Summary: "Top-up MSISDN",
		Domain: "Billing",
		Reads:  []string{"party.party.contact_medium"},
		Writes: []string{"payment.payment.payment", "prepay.prepay.topup"}},

	// ── Service level / speed / migration ──────────────────────
	{Method: "POST", Path: "/service/speed-change/{serviceId}", Summary: "Speed Change",
		Domain: "Service",
		Writes: []string{"service.service.service_value", "service.public.service_history_unnest"}},
	{Method: "POST", Path: "/service/level-change/{serviceId}", Summary: "Level Change",
		Domain: "Service",
		Writes: []string{"service.service.service_value"}},
	{Method: "POST", Path: "/service/revoke-level-migration/{parentServiceId}", Summary: "Revoke Level Migration",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/migrate", Summary: "Migrate Product",
		Domain: "Service",
		Writes: []string{"service.service.service_order_item", "product.product.product_order_item"}},
	{Method: "POST", Path: "/service/revoke-migration/{parentServiceId}", Summary: "Revoke Migration",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},

	// ── Cancellation flow ──────────────────────────────────────
	{Method: "POST", Path: "/service/cancel/{productId}", Summary: "Cancel Service",
		Domain: "Service",
		Writes: []string{"service.service.service_order", "service.public.service_history_unnest"}},
	{Method: "POST", Path: "/service/cancel/query/{product-id}", Summary: "Query Cancel",
		Domain: "Service",
		Reads:  []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/scheduled-cancel/{parentServiceId}", Summary: "Pre-cancel Scheduled",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/revoke-scheduled-cancel/{parentServiceId}", Summary: "Revoke Scheduled Cancel",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/revoke-precancel/{parentServiceId}", Summary: "Revoke Pre-cancel",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/revoke/{serviceId}", Summary: "Revoke Action",
		Domain: "Service",
		Writes: []string{"service.service.service_order"}},
	{Method: "POST", Path: "/service/revoke-addon/{serviceId}", Summary: "Revoke Addon",
		Domain: "Service",
		Writes: []string{"service.service.service_order_item"}},

	// ── Device / CPE ops ───────────────────────────────────────
	{Method: "POST", Path: "/service/return-device", Summary: "Return Device",
		Domain: "Service",
		Writes: []string{"product.product.product_inventory_history", "logistics.logistics.return_order"}},
	{Method: "POST", Path: "/service/log-tower-incident/{incidentId}", Summary: "Escalate to NOC",
		Domain: "Support",
		Writes: []string{"snowflake.public.ticket", "snowflake.public.entity_ticket"}},
	{Method: "POST", Path: "/service/de-latch-user", Summary: "De-latch User",
		Domain: "Service",
		Writes: []string{"service.service.service_order", "party.party.individual"}},

	// ── OTA / APN push ─────────────────────────────────────────
	{Method: "POST", Path: "/service/send-ota-settings/{msisdn}", Summary: "Send OTA Settings",
		Domain: "Service",
		Reads:  []string{"party.party.contact_medium"},
		Writes: []string{"communication.notification.sms", "communication.notification.sms_history"}},
	{Method: "POST", Path: "/service/send-apn-settings/msisdn/{msisdn}/imsi/{imsi}", Summary: "Send APN Settings",
		Domain: "Service",
		Reads:  []string{"party.party.contact_medium"},
		Writes: []string{"communication.notification.sms", "communication.notification.sms_history"}},
	{Method: "PATCH", Path: "/service/international-dialing/{service-id}/{user-id}/{msisdn}", Summary: "OTA International Dialing",
		Domain: "Service",
		Writes: []string{"service.service.service_value", "communication.notification.sms"}},
	{Method: "PATCH", Path: "/service/international-dialing/{msisdn}/{enable}", Summary: "OTA International Dialing (simple)",
		Domain: "Service",
		Writes: []string{"service.service.service_value", "communication.notification.sms"}},

	// ── Legacy CPE / speed tests / reboot ──────────────────────
	{Method: "POST", Path: "/service/legacy-cpe/upload-speed-test", Summary: "Upload Speed Test",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history"}},
	{Method: "POST", Path: "/service/legacy-cpe/reboot", Summary: "Reboot Device",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history"}},
	{Method: "POST", Path: "/service/legacy-cpe/poll-last-operation-status", Summary: "Poll Operation Status",
		Domain: "Service",
		Reads:  []string{"snowflake.public.agent_action_history", "snowflake.public.agent_action_current"}},
	{Method: "POST", Path: "/service/legacy-cpe/download-speed-test", Summary: "Download Speed Test",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history"}},
	{Method: "POST", Path: "/service/device/set-wifi/{id}", Summary: "Device Set Wifi",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history", "product.product.product_inventory_history"}},
	{Method: "POST", Path: "/service/101/speed-test/{imei}", Summary: "101 Speed Test",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history"}},
	{Method: "POST", Path: "/service/101/reboot", Summary: "101 Reboot",
		Domain: "Service",
		Writes: []string{"snowflake.public.agent_action_history"}},

	// ── Raindrop zone check ────────────────────────────────────
	{Method: "POST", Path: "/raindrop/zone-check", Summary: "Zone Check",
		Domain: "Catalogue",
		Reads:  []string{"raindrop.raindrop.coverage", "geographic.geographic.address"}},

	// ── Product lifecycle ──────────────────────────────────────
	{Method: "POST", Path: "/product/upgrade/{id}", Summary: "Upgrade Product",
		Domain: "Catalogue",
		Writes: []string{"product.product.product_order_item", "service.service.service_order_item"}},
	{Method: "POST", Path: "/product/swap-product/{id}", Summary: "Product Swap",
		Domain: "Catalogue",
		Writes: []string{"product.product.product_order_item"}},
	{Method: "POST", Path: "/product/migrate/{id}", Summary: "Migrate Product",
		Domain: "Catalogue",
		Writes: []string{"product.product.product_order_item", "service.service.service_order_item"}},
	{Method: "POST", Path: "/product/migrate/{id}/immediate", Summary: "Migrate Immediate",
		Domain: "Catalogue",
		Writes: []string{"product.product.product_order_item", "service.service.service_order_item"}},

	// ── Payment plans / promise-to-pay ─────────────────────────
	{Method: "GET", Path: "/paymentPlan/{userId}", Summary: "Get Payment Plans",
		Domain: "Billing",
		Reads:  []string{"account.account.promise_to_pay", "account.account.promise_to_pay_item"}},
	{Method: "POST", Path: "/paymentPlan/{userId}", Summary: "Create Payment Plan",
		Domain: "Billing",
		Writes: []string{"account.account.promise_to_pay", "account.account.promise_to_pay_item", "account.account.promise_to_pay_history"}},
	{Method: "PATCH", Path: "/paymentPlan/subscriptionPlan/{userId}", Summary: "Update Plan Date",
		Domain: "Billing",
		Writes: []string{"account.account.promise_to_pay", "account.account.promise_to_pay_history"}},
	{Method: "GET", Path: "/account/promise-to-pay/{userId}", Summary: "Get Promise-to-Pay",
		Domain: "Billing",
		Reads:  []string{"account.account.promise_to_pay", "account.account.promise_to_pay_item"}},
	{Method: "POST", Path: "/account/promise-to-pay/{userId}", Summary: "Create Promise-to-Pay",
		Domain: "Billing",
		Writes: []string{"account.account.promise_to_pay", "account.account.promise_to_pay_history"}},
	{Method: "POST", Path: "/account/promise-to-pay/validate/{userId}", Summary: "Validate Promise-to-Pay",
		Domain: "Billing",
		Reads:  []string{"account.account.promise_to_pay", "account.account.promise_to_pay_item_history"}},

	// ── OTP / registration ─────────────────────────────────────
	{Method: "POST", Path: "/otp/validate", Summary: "Validate OTP",
		Domain: "Identity",
		Reads:  []string{"digital.digital.credential"},
		Notes:  "OTPs live in digital.digital.credential as short-lived rows."},
	{Method: "POST", Path: "/otp/send", Summary: "Send OTP",
		Domain: "Identity",
		Writes: []string{"digital.digital.credential", "communication.notification.sms"}},
	{Method: "POST", Path: "/account/user-registration/otp", Summary: "Register User OTP",
		Domain: "Identity",
		Writes: []string{"party.party.individual", "digital.digital.credential", "communication.notification.sms"}},

	// ── Organization / CIPC ────────────────────────────────────
	{Method: "POST", Path: "/organization/cipc/verify", Summary: "Verify CIPC",
		Domain: "Identity",
		Reads:  []string{"party.party.organization", "party.party.organization_identification"}},

	// ── Orders (fulfilment / logistics) ────────────────────────
	{Method: "POST", Path: "/order/reprovision", Summary: "Reprovision Delivery",
		Domain: "Sales",
		Writes: []string{"logistics.logistics.order", "logistics.logistics.order_line"}},
	{Method: "POST", Path: "/order/reprovision-to-store/{orderNumber}", Summary: "Reprovision to Store",
		Domain: "Sales",
		Writes: []string{"logistics.logistics.order"}},
	{Method: "POST", Path: "/order/redeliver/{orderNumber}", Summary: "Redeliver",
		Domain: "Sales",
		Writes: []string{"logistics.logistics.order", "logistics.logistics.order_history"}},
	{Method: "POST", Path: "/order/force-activate/{userId}", Summary: "Activate Service",
		Domain: "Sales",
		Writes: []string{"service.service.service_order", "product.product.product_order_item", "logistics.logistics.order"}},
	{Method: "POST", Path: "/order/cancel-order", Summary: "Cancel Order",
		Domain: "Sales",
		Writes: []string{"product.product.product_order_item", "logistics.logistics.order"}},
	{Method: "POST", Path: "/order/bulk-force-activate/{userId}", Summary: "Bulk Force Activate",
		Domain: "Sales",
		Writes: []string{"service.service.service_order", "product.product.product_order_item"}},

	// ── Sales / shopping cart ──────────────────────────────────
	{Method: "POST", Path: "/api/sales/update-shopping-cart/{id}", Summary: "Update Cart",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.shopping_cart", "shopping.shopping.cart_item"}},
	{Method: "POST", Path: "/api/sales/shopping-cart-add-voucher/{id}/voucher/{voucherToken}", Summary: "Add Voucher",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.shopping_cart", "shopping.shopping.cart_price"}},
	{Method: "POST", Path: "/api/sales/open-shopping-cart-by-user/{userId}", Summary: "Open Cart by User",
		Domain: "Sales",
		Reads:  []string{"shopping.shopping.shopping_cart", "party.party.individual"}},
	{Method: "POST", Path: "/api/sales/create-shopping-cart", Summary: "Create Cart",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.shopping_cart"}},
	{Method: "POST", Path: "/api/sales/checkout-shopping-cart/{id}", Summary: "Checkout Cart",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.shopping_cart", "product.product.product_order_item", "payment.payment.payment"}},
	{Method: "POST", Path: "/api/sales/checkout-product-order/{id}", Summary: "Checkout Product Order",
		Domain: "Sales",
		Writes: []string{"product.product.product_order_item", "payment.payment.payment"}},
	{Method: "POST", Path: "/api/sales/checkout-csi/{id}", Summary: "Checkout CSI",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.shopping_cart"}},
	{Method: "PATCH", Path: "/api/sales/shopping-cart/{cartId}/discount", Summary: "Apply Discount",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.cart_price", "shopping.shopping.price_alteration"}},
	{Method: "PATCH", Path: "/api/sales/shopping-cart/{cartId}/discount/remove", Summary: "Remove Discount",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.price_alteration"}},
	{Method: "PATCH", Path: "/api/sales/cart-item/migrate/{id}", Summary: "Alter Cart Item Offering",
		Domain: "Sales",
		Writes: []string{"shopping.shopping.cart_item"}},

	// ── Account / billing / debit / credit ─────────────────────
	{Method: "POST", Path: "/account/take-my-money-now", Summary: "Take My Money Now",
		Domain: "Billing",
		Writes: []string{"payment.payment.payment", "payment.payment.peach_transaction"}},
	{Method: "POST", Path: "/account/reset-username", Summary: "Reset Username",
		Domain: "Identity",
		Writes: []string{"party.party.individual", "digital.digital.credential"}},
	{Method: "POST", Path: "/account/reset-password/{email}", Summary: "Reset Password",
		Domain: "Identity",
		Writes: []string{"digital.digital.credential", "communication.notification.email", "communication.notification.email_history"}},
	{Method: "POST", Path: "/account/resend-order-link", Summary: "Resend Order Link",
		Domain: "Sales",
		Reads:  []string{"logistics.logistics.order"},
		Writes: []string{"communication.notification.email", "communication.notification.sms"}},
	{Method: "POST", Path: "/account/refund", Summary: "Refund",
		Domain: "Billing",
		Writes: []string{"payment.payment.refund", "payment.payment.payment", "payment.payment.peach_transaction"}},
	{Method: "POST", Path: "/account/policy/{policy}/user/{userId}", Summary: "Update Policy State",
		Domain: "Identity",
		Writes: []string{"party.party.individual", "party.party.characteristic"}},
	{Method: "POST", Path: "/account/pay-now/peach", Summary: "Send Peach Pay-Now",
		Domain: "Billing",
		Writes: []string{"payment.payment.peach_transaction", "communication.notification.sms"}},
	{Method: "POST", Path: "/account/pay-now/pay-at", Summary: "Send Pay@ Pay-Now",
		Domain: "Billing",
		Writes: []string{"payment.payment.pay_at_transaction", "communication.notification.sms"}},
	{Method: "POST", Path: "/account/notify", Summary: "Create Notification",
		Domain: "Identity",
		Writes: []string{"communication.notification.email", "communication.notification.sms", "communication.notification.whatsapp", "communication.notification.push_history"}},
	{Method: "POST", Path: "/account/debit", Summary: "Send Debit",
		Domain: "Billing",
		Writes: []string{"payment.payment.payment", "account.account.account_balance_history"}},
	{Method: "POST", Path: "/account/credit", Summary: "Send Credit",
		Domain: "Billing",
		Writes: []string{"payment.payment.payment", "account.account.account_balance_history"}},
	{Method: "POST", Path: "/account/create", Summary: "Create User Account",
		Domain: "Identity",
		Writes: []string{"party.party.individual", "party.party.contact_medium", "account.account.billing_account", "account.account.financial_account"}},
	{Method: "POST", Path: "/account/cancel-payment-link/{referenceId}", Summary: "Cancel Payment Link",
		Domain: "Billing",
		Writes: []string{"payment.payment.peach_transaction"}},
	{Method: "POST", Path: "/account/billingAccount/transfer/{fromAccountId}", Summary: "Transfer Balance",
		Domain: "Billing",
		Writes: []string{"account.account.billing_account", "account.account.account_balance", "account.account.account_balance_history"}},
	{Method: "POST", Path: "/account/billing/itemized/{userId}/{msisdn}", Summary: "Itemized Billing",
		Domain: "Billing",
		Reads:  []string{"customer.public.invoices", "customer.public.invoice_items", "customer.customer_bill.financial_statement"}},
	{Method: "POST", Path: "/account/billing/invoice/{userId}/{billId}", Summary: "Invoice Notify",
		Domain: "Billing",
		Reads:  []string{"customer.public.invoices"},
		Writes: []string{"communication.notification.email", "communication.notification.email_history"}},
	{Method: "PATCH", Path: "/account/policy/{serviceId}", Summary: "Update Service Policy",
		Domain: "Service",
		Writes: []string{"service.service.service_value"}},
}
